const AUTH_STORAGE_KEY = 'wa_cert_authenticated';
const REACT_CHALLENGE_AUTH = 'REACT-CHALLENGE-AUTH';
const REACT_CHALLENGE_USER_PREFERENCES = 'REACT-CHALLENGE-USER-PREFERENCES';

export { AUTH_STORAGE_KEY, REACT_CHALLENGE_AUTH, REACT_CHALLENGE_USER_PREFERENCES };
